version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - USER_SERVICE_URL=http://localhost:8080/api/users
      - INVENTORY_SERVICE_URL=localhost:9000
      - TRANSACTION_SERVICE_URL=http://localhost:8082